### ISSUE TITLE
Inline Dataview field styling in infoboxes doesn't seem to display

### ISSUE THREAD

**Issue by PackysSportsBar** [Bluemoondragon07/Wikipedia-Theme#4]
This could be me misunderstanding the necessary syntax, but I haven't been able to get the inline Dataview field styling to show up. As an example, variations on the line `> Test key:: Test value` all just result in:
![image](https://user-images.githubusercontent.com/47766582/233235395-0e41e485-276f-419b-be1e-3f232243c52f.png)

I have also tried the theme on a new vault, so I don't think it's due to any plugin or customization conflicts.

**Comment by Bluemoondragon07** [comment]
The styling will only apply to dataview fields enclosed in brackets. For example, `[Test key:: Test value]`. 

I would like to extend the styling to normal dataview fields, but unfortunately, only bracket-enclosed fields have specific selectors.
