### ISSUE TITLE
Installing could be more clear

### ISSUE THREAD

**Issue by xuijuthub** [Bluemoondragon07/Wikipedia-Theme#9]
Hi. I'm quite new to obsidian, it was a little struggle to understand the fact, that the theme folder has to be called exactly Wikipedia. Perhaps packing the release as a nested folder would be a viable solution. BTW, thanks for the style, I highly appreciate the work!!

**Comment by Bluemoondragon07** [comment]
Glad you like it! There are also two easier ways to install:
1. Copy the content of `theme.css` and put it in a `Wikipedia.css` file in `/.obsidian/themes`
2. Go to the community theme store inside Obsidian, search "Wikipedia", and install or update.

I am not really familiar with adding files to releases, but I will consider doing it in the future!
